#!/usr/bin/env python3
"""
Valid joke categories for the joke submission pipeline.

Categories marked with * require manual review for appropriateness.
"""

# Maximum number of categories that can be assigned to a single joke
MAX_CATEGORIES_PER_JOKE = 10

# Valid joke categories (alphabetically sorted)
VALID_CATEGORIES = [
    "30th Birthday",
    "40th Birthday",
    "4th of July",
    "50th Birthday",
    "60th Birthday",
    "911",
    "AA",
    "Aboriginal",
    "Abraham Lincoln",
    "Academic",
    "Account",
    "Accountant",
    "Accounting",
    "Actor",
    "Ad",
    "Addiction",
    "Afghanistan",
    "Africa",
    "Age",
    "Aging",
    "AI",
    "Air Conditioning",
    "Air Force",
    "Airplane",
    "Akpos",
    "Alabama",
    "Alcohol",
    "Alcoholic",
    "Alexa",
    "Algebra",
    "Alien",
    "Alligator",
    "Alpaca",
    "America",
    "American Airlines",
    "Amish",
    "Anatomy",
    "Animal",
    "Animals",
    "Anime",
    "Anniversary",
    "Ant",
    "Anti-joke",
    "Apple",
    "April Fools",
    "April",
    "Arabian",
    "Arabic",
    "Architect",
    "Architecture",
    "Aristocrat",
    "Army",
    "Arsenal F.C.",
    "Art",
    "Asia",
    "Atheist",
    "Attorney",
    "Audit",
    "Auditor",
    "August",
    "Aunt",
    "Australia",
    "Autism",
    "Autistic",
    "Autumn",
    "Aviation",
    "Avocado",
    "Baby",
    "Back to School",
    "Bacon",
    "Baked",
    "Baker",
    "Bakery",
    "Baking",
    "Bald",
    "Ball",
    "Balloon",
    "Banana",
    "Band",
    "Bank",
    "Banker",
    "Bar",
    "Barack Obama",
    "Barbecue",
    "Bartender",
    "Baseball",
    "Basketball",
    "Bass Guitar",
    "Bass Player",
    "Bat",
    "Bath",
    "Bathroom",
    "Batman",
    "Beach",
    "Bean",
    "Bear",
    "Beard",
    "Beaver",
    "Beer",
    "Belgium",
    "Bengal",
    "Best Friend",
    "Best Man",
    "Bible",
    "Bike",
    "Bingo",
    "Biology",
    "Bird",
    "Birthday",
    "Bison",
    "Black Friday",
    "Blind",
    "Blonde",
    "Blue",
    "BMW",
    "Boat",
    "Boating",
    "Body",
    "Bomb",
    "Bomber",
    "Bombing",
    "Bone",
    "Book",
    "Boomer",
    "Boss",
    "Bowler",
    "Bowling",
    "Brain",
    "Bread",
    "Breakfast",
    "Breaking up",
    "Breakup",
    "Brick",
    "Britain",
    "British",
    "Broccoli",
    "Brother",
    "Buddhist",
    "Buffalo",
    "Bug",
    "Bunny",
    "Burger",
    "Business",
    "Businessman",
    "Butt",
    "Butter",
    "Butterfly",
    "Cactus",
    "Café",
    "Cake",
    "Calculus",
    "Camel",
    "Camp",
    "Camping",
    "Canada",
    "Candy",
    "Cannibal",
    "Car",
    "Carrot",
    "Cartoon",
    "Cash",
    "Cat",
    "Catholic",
    "Cattle",
    "Celebrity",
    "Cemetery",
    "ChatGPT",
    "Cheese",
    "Chef",
    "Chelsea",
    "Chemist",
    "Chemistry",
    "Chess",
    "Chevy",
    "Chicken",
    "Chocolate",
    "Christian",
    "Christianity",
    "Christmas Cracker",
    "Christmas Tree",
    "Christmas",
    "Chuck Norris",
    "Church",
    "Civil Engineer",
    "Civil Engineering",
    "Cleaner",
    "Cleaning",
    "Clock",
    "Clown",
    "Code",
    "Coder",
    "Coffee",
    "Cold",
    "Colonoscopy",
    "Comedian",
    "Comedy",
    "Comic",
    "Computer Coding",
    "Computer Programming",
    "Computer Science",
    "Computer Scientist",
    "Computer",
    "Computing",
    "Construction",
    "Cook",
    "Cookie",
    "Cooking",
    "Cool",
    "Cop",
    "Corn",
    "Corny",
    "Corporate",
    "Country",
    "Couple",
    "Courtroom",
    "Covid",
    "Cow",
    "Cowboy",
    "Crab",
    "Cracker",
    "Cricket",
    "Cricketer",
    "Crocodile",
    "Cross the Road",
    "Crush",
    "Current Events",
    "Cycling",
    "Dad Jokes",
    "Dad",
    "Dallas Cowboys",
    "Dance",
    "Dancing",
    "Dark Humor",
    "Darkness",
    "Data Science",
    "Dating",
    "Day",
    "Deaf",
    "Death",
    "December",
    "Deer",
    "Definition",
    "Dental",
    "Dentist",
    "Depressed",
    "Depression",
    "Developer",
    "Diabetes",
    "Diarrhea",
    "Dieting",
    "Dilbert",
    "Dinosaur",
    "Disney",
    "Divorce",
    "DnD",
    "Doctor",
    "Dog",
    "Dolphin",
    "Donald Trump",
    "Donkey",
    "Double Meaning",
    "Doughnut",
    "Dragon",
    "Draw",
    "Drawing",
    "Driving",
    "Drummer",
    "Dry",
    "Duck",
    "Dumb",
    "Dyslexia",
    "Ear",
    "Earthquake",
    "Easter Bunny",
    "Easter",
    "Economics",
    "Economy",
    "Education",
    "Egg",
    "Egypt",
    "Elderly People",
    "Electrician",
    "Electricity",
    "Elephant",
    "Elevator",
    "Elf on the Shelf",
    "Elf",
    "Elon Musk",
    "Emoji",
    "Employee",
    "Employment",
    "Engineer",
    "Engineering",
    "English Teacher",
    "English",
    "Exam Tension",
    "Exam",
    "Exercise",
    "Eye",
    "Face",
    "Facebook",
    "Fall",
    "Falling",
    "Family",
    "Famous",
    "Farm",
    "Farmer",
    "Farming",
    "Fart",
    "Father",
    "Father's Day",
    "February",
    "Feminist",
    "Fighting",
    "Finance",
    "Fire",
    "Firefighter",
    "Fish",
    "Fisherman",
    "Fishing",
    "Fitness",
    "Flamingo",
    "Flat Earther",
    "Flight",
    "Flirting",
    "Flower",
    "Flu",
    "Flying",
    "Food",
    "Foot",
    "Footballer",
    "Ford",
    "Forehead",
    "Fortnite",
    "Fox",
    "French",
    "Friday the 13th",
    "Friday",
    "Friendship",
    "Frog",
    "Fruit",
    "Funeral",
    "Game",
    "Gamer",
    "Garden",
    "Gardener",
    "Gardening",
    "Gasoline",
    "Gen Z",
    "Geography",
    "Geologist",
    "Geology",
    "Geometry",
    "Getting Older",
    "Ghost",
    "Gift",
    "Ginger",
    "Giraffe",
    "Girlfriend",
    "Glass",
    "Glasses",
    "Gnome",
    "Goat",
    "God",
    "Golf",
    "Golfer",
    "Goofy",
    "Google",
    "Goose",
    "Graduation",
    "Grammar",
    "Grandma",
    "Grandpa",
    "Greece",
    "Greek",
    "Guess What",
    "Guitar Player",
    "Guitar",
    "Guitarist",
    "Gun",
    "Gym",
    "Hair",
    "Haircut",
    "Hairdresser",
    "Hairline",
    "Halloween",
    "Hand",
    "Happiness",
    "Happy",
    "Harry Potter",
    "Harry Styles",
    "Head",
    "Healthy",
    "Heart",
    "Height",
    "Helen Keller",
    "Hell",
    "Hen",
    "Hike",
    "Hiker",
    "Hiking",
    "Hip Replacement",
    "Hip Surgery",
    "Historical Figures",
    "History",
    "Hoarder",
    "Hockey",
    "Holiday",
    "Home Builder",
    "Horror",
    "Horse",
    "Hospital",
    "Hot Dog",
    "Hot",
    "Hotel",
    "Human Resources",
    "Hump Day",
    "Hunting",
    "Husband",
    "Ice Cream",
    "Ice",
    "Idea",
    "IKEA",
    "Illness",
    "In Love",
    "Independence Day",
    "India",
    "Indian",
    "Insect",
    "Instagram",
    "Insult",
    "Insurance",
    "Intelligence",
    "Intelligent",
    "International",
    "Internet",
    "Interview",
    "iPhone",
    "Ireland",
    "Irish",
    "IT",
    "Italian",
    "Italy",
    "Jailhouse",
    "January",
    "Japan",
    "Jesus",
    "Job",
    "Juan",
    "July",
    "June",
    "Kangaroo",
    "Karen",
    "Ketchup",
    "Kids",
    "Kindergarten",
    "Kissing",
    "Knee",
    "Knock-Knock",
    "Koala",
    "Korea",
    "Labor Day",
    "Laffy Taffy",
    "Laughter",
    "Law",
    "Lawyer",
    "Leaf",
    "League of Legends",
    "League",
    "Lego",
    "Lemon",
    "Leprechaun",
    "Lettuce",
    "Library",
    "Life",
    "Light Bulb",
    "Light",
    "Lion",
    "Little Johnny",
    "Liverpool",
    "Llama",
    "Lobster",
    "Logic",
    "Long",
    "Love",
    "Lunch",
    "Man",
    "Management",
    "Manager",
    "Manchester United",
    "Mango",
    "March",
    "Marine",
    "Mario",
    "Marketer",
    "Marketing",
    "Marriage",
    "Marvel",
    "Math Teacher",
    "Math",
    "Mathematician",
    "May",
    "McDonald's",
    "Meat",
    "Mechanic",
    "Medical",
    "Mermaid",
    "Message",
    "Messi",
    "Mexico",
    "Michael Jackson",
    "Military",
    "Milk",
    "Millennial",
    "Minecraft",
    "Minion",
    "Mom",
    "Monday",
    "Money",
    "Monkey",
    "Month",
    "Moon",
    "Moose",
    "Mormon",
    "Morning",
    "Mosquito",
    "Moth",
    "Mother's Day",
    "Mother-in-Law",
    "Motivation",
    "Motivational",
    "Motorbike",
    "Motorcycle",
    "Mouse",
    "Movie",
    "Mummy",
    "Mushroom",
    "Music",
    "Muslim",
    "Mustache",
    "Nacho Cheese",
    "Nacho",
    "Name",
    "Narcissism",
    "Narcissist",
    "National Pi Day",
    "Navy",
    "Nerd",
    "New Year Resolution",
    "New Year",
    "New York",
    "No Arms No Legs",
    "Non-Vegetarian",
    "North Korea",
    "Northerner",
    "Nose",
    "November",
    "Number",
    "Nun",
    "Nurse",
    "Nut",
    "Observational",
    "Ocean",
    "October",
    "Octopus",
    "Office",
    "Ohio",
    "Old Age",
    "Old Fashioned",
    "Old",
    "On Time",
    "One-Liners",
    "Onion",
    "Online",
    "Operation",
    "Orange",
    "Otter",
    "Owl",
    "Paint",
    "Painter",
    "Pancake",
    "Panda",
    "Paper",
    "Parent",
    "Parrot",
    "Party",
    "Pasta",
    "Peach",
    "Peanut",
    "Pee",
    "Pencil",
    "Penguin",
    "Penny",
    "Pepito",
    "Periodic Table",
    "Pharmacist",
    "Pharmacy",
    "PhD",
    "Philosopher",
    "Philosophy",
    "Phone",
    "Photo",
    "Physical Therapist",
    "Physicist",
    "Physics",
    "Pi",
    "Pianist",
    "Piano",
    "Pick up Lines",
    "Pickle",
    "Picture",
    "Pie",
    "Pig",
    "Pilot",
    "Pineapple",
    "Pinterest",
    "Pirate",
    "Pizza",
    "Planet",
    "Plant",
    "Planting",
    "Play",
    "Playing",
    "Plumber",
    "Poem",
    "Poet",
    "Poetry",
    "Pokémon",
    "Poland",
    "Polar Bear",
    "Police Officer",
    "Police",
    "Policeman",
    "Political",
    "Politician",
    "Politics",
    "Poop",
    "Poor",
    "Pop Culture",
    "Popcorn",
    "Popsicle Stick",
    "Popsicle",
    "Portugal",
    "Portuguese",
    "Potato",
    "Poverty",
    "Pregnant",
    "Preschool",
    "Preschooler",
    "Priest",
    "Prison",
    "Prisoner",
    "Profession",
    "Programmer",
    "Pronoun",
    "Psychiatrist",
    "Psychiatry",
    "Psychology",
    "Puerto Rico",
    "Pumpkin",
    "Pun",
    "Punchline",
    "Puzzle",
    "Question",
    "Rabbit",
    "Race",
    "Racing",
    "Ramadan",
    "Rapper",
    "Rat",
    "Reading",
    "Real Estate Agent",
    "Real Estate",
    "Red Panda",
    "Redhead",
    "Redneck",
    "Registered Nurse",
    "Reindeer",
    "Relationship",
    "Relationships",
    "Religion",
    "Restaurant",
    "Restroom",
    "Retirement",
    "Roast",
    "Roblox",
    "Robot",
    "Rock",
    "Roman",
    "Romance",
    "Romantic",
    "Rome",
    "Roof",
    "Roofer",
    "Roofing",
    "Rooster",
    "Rose",
    "Run",
    "Runner",
    "Running",
    "Sad",
    "Sadness",
    "Sailor",
    "Salad",
    "Sales",
    "San Francisco 49er",
    "Sandwich",
    "Santa",
    "Santa-Banta",
    "Satire",
    "Saturday",
    "Sausage",
    "Scarecrow",
    "Scared",
    "Scary",
    "School",
    "Science",
    "Scientist",
    "Sea",
    "Seafood",
    "Seagull",
    "Season",
    "Self-Deprecating",
    "Senior",
    "September",
    "Shakespeare",
    "Shark",
    "Sheep",
    "Shoe",
    "Short People",
    "Shrek",
    "Singer",
    "Single",
    "Siri",
    "Sister",
    "Skeleton",
    "Skinny",
    "Slave",
    "Sleep",
    "Sleeping",
    "Sloth",
    "Small",
    "Smart",
    "Smiling",
    "Smoke",
    "Smoker",
    "Smoking",
    "Snail",
    "Snake",
    "Snow",
    "Snowman",
    "So Dumb",
    "So Fat",
    "So Hot",
    "So Old",
    "So Short",
    "So Stupid",
    "So Ugly",
    "Soccer",
    "Sofa King",
    "Song",
    "Southerner",
    "Space",
    "Spain",
    "Spanish Language",
    "Spanish",
    "Spectacles",
    "Speech",
    "Spell",
    "Spelling",
    "Spider",
    "Spider-Man",
    "SpongeBob",
    "Sport",
    "Sports",
    "Spring",
    "Squirrel",
    "St. Patrick's Day",
    "Star Trek",
    "Star Wars",
    "Statistic",
    "Statistician",
    "Status",
    "Stephen Hawking",
    "Strange",
    "Stranger Things",
    "Strawberry",
    "Street",
    "Stress",
    "Student",
    "Study",
    "Studying",
    "Stupid",
    "Submarine",
    "Summer",
    "Sun",
    "Sunday",
    "Sunflower",
    "Super Mario",
    "Superhero",
    "Surgical",
    "Sushi",
    "Sweating Like",
    "Sweden",
    "Sweet",
    "Swim",
    "Swimming Pool",
    "Swimming",
    "T-Rex",
    "T-Shirt",
    "Taco",
    "Tailor",
    "Talk Show",
    "Tall People",
    "Tattoo",
    "Tax",
    "Taylor Swift",
    "Tea",
    "Teacher",
    "Teaching",
    "Technology",
    "Teenager",
    "Television",
    "Tennis",
    "Tesla",
    "Texas",
    "Text Message",
    "Text",
    "Thanksgiving",
    "Theater",
    "Therapist",
    "Therapy",
    "Thesaurus",
    "Thursday",
    "Tiger Woods",
    "Tiger",
    "TikTok",
    "Time",
    "Tinder",
    "Toast",
    "Toaster",
    "Toe",
    "Toilet Paper",
    "Toilet Roll",
    "Toilet",
    "Tomato",
    "Tooth",
    "Topical",
    "Tractor",
    "Train",
    "Travel",
    "Traveler",
    "Traveling",
    "Tree",
    "Trick",
    "Truck",
    "Trucker",
    "Trucking",
    "Tuesday",
    "Tuna",
    "Turkey",
    "Turtle",
    "Tweet",
    "Twin",
    "Twitter",
    "U.S. Marine",
    "Ugly",
    "UK",
    "Uncle",
    "Unicorn",
    "Uranus",
    "USA",
    "Valentine's Day",
    "Vampire",
    "Vegan",
    "Vegetable",
    "Vegetarian",
    "Vehicle",
    "Veteran's Day",
    "Video Game",
    "Video",
    "Viking",
    "Viola",
    "Violist",
    "Virus",
    "Volleyball",
    "Walks Into a Bar",
    "War",
    "Water",
    "Watermelon",
    "Weather",
    "Website",
    "Wedding",
    "Wednesday",
    "Weekend",
    "Werewolf",
    "Whale",
    "What Did",
    "What Do",
    "What Is",
    "What",
    "WhatsApp",
    "Wheelchair",
    "Wife",
    "Wine",
    "Winter",
    "Witch",
    "Witchcraft",
    "Wolf",
    "Woman",
    "Wood",
    "Wooden",
    "Word",
    "Wordplay",
    "Work at Home",
    "Work Colleague",
    "Work",
    "Workday",
    "Worker",
    "Working",
    "Workout",
    "Workplace",
    "World of Warcraft",
    "Writing",
    "Yo Daddy",
    "Yo Mama",
    "Yoda",
    "Yoga",
    "You Might Be",
    "You So",
    "YouTube",
    "YouTuber",
    "Zombie",
    "Zoo",
    "Zoom",
]
