#!/usr/bin/env python3
"""
Valid joke categories for the joke submission pipeline.

Categories marked with * require manual review for appropriateness.
"""

# Maximum number of categories that can be assigned to a single joke
MAX_CATEGORIES_PER_JOKE = 10

# Valid joke categories (alphabetically sorted)
VALID_CATEGORIES = [
    "30th Birthday",
    "40th Birthday",
    "4th of July",
    "50th Birthday",
    "60th Birthday",
    "911",
    "AA",
    "Aboriginal",
    "Account",
    "Accountant",
    "Accounting",
    "Actor",
    "Ad",
    "Addiction",
    "Africa",
    "Age",
    "Aging",
    "AI",
    "Air Conditioning",
    "Air Force",
    "Airplane",
    "Akpos",
    "Alabama",
    "Alcohol",
    "Alcoholic",
    "Alexa",
    "Algebra",
    "Alien",
    "Alligator",
    "Alpaca",
    "America",
    "American Airlines",
    "Amish",
    "Anatomy",
    "Animal",
    "Animals",
    "Anime",
    "Anniversary",
    "Ant",
    "Ant and Elephant",
    "Anti",
    "Anti-Jokes",
    "Apple",
    "April",
    "April Fools",
    "Arabian",
    "Arabic",
    "Architect",
    "Architecture",
    "Aristocrat",
    "Army",
    "Arsenal F.C.",
    "Art",
    "Asia",
    "Atheist",
    "Attorney",
    "Audit",
    "Auditor",
    "August",
    "Aunt",
    "Australia",
    "Autism",
    "Autistic",
    "Autumn",
    "Aviation",
    "Avocado",
    "Baby",
    "Back to School",
    "Bacon",
    "Baked",
    "Baker",
    "Bakery",
    "Baking",
    "Bald",
    "Ball",
    "Balloon",
    "Banana",
    "Band",
    "Bank",
    "Banker",
    "Bar",
    "Barbecue",
    "Bartender",
    "Baseball",
    "Basketball",
    "Bass Guitar",
    "Bass Player",
    "Bat",
    "Bath",
    "Bathroom",
    "Batman",
    "Beach",
    "Bean",
    "Bear",
    "Beard",
    "Beaver",
    "Beer",
    "Bengal",
    "Best Friend",
    "Best Man",
    "Bible",
    "Bike",
    "Bingo",
    "Biology",
    "Bird",
    "Birthday",
    "Bison",
    "Black Friday",
    "Blind",
    "Blonde",
    "Blue",
    "BMW",
    "Boat",
    "Boating",
    "Body",
    "Bomb",
    "Bomber",
    "Bombing",
    "Bone",
    "Book",
    "Boomer",
    "Boss",
    "Bowler",
    "Bowling",
    "Brain",
    "Bread",
    "Breakfast",
    "Breaking up",
    "Breakup",
    "Brick",
    "Britain",
    "British",
    "Broccoli",
    "Brother",
    "Buddhist",
    "Buffalo",
    "Bug",
    "Bunny",
    "Burger",
    "Business",
    "Businessman",
    "Butt",
    "Butter",
    "Butterfly",
    "Cactus",
    "Café",
    "Cake",
    "Calculus",
    "Camel",
    "Camp",
    "Camping",
    "Canada",
    "Candy",
    "Cannibal",
    "Car",
    "Carrot",
    "Cartoon",
    "Cash",
    "Cat",
    "Catholic",
    "Catholic Church",
    "Cattle",
    "Celebrity",
    "Cemetery",
    "ChatGPT",
    "Cheese",
    "Chef",
    "Chelsea",
    "Chemist",
    "Chemistry",
    "Chess",
    "Chevy",
    "Chicken",
    "Chocolate",
    "Christian",
    "Christianity",
    "Christmas",
    "Christmas Cracker",
    "Christmas Tree",
    "Chuck Norris",
    "Church",
    "Civil Engineer",
    "Civil Engineering",
    "Cleaner",
    "Cleaning",
    "Clock",
    "Clown",
    "Code",
    "Coder",
    "Coffee",
    "Cold",
    "Colonoscopy",
    "Comedian",
    "Comedy",
    "Comic",
    "Computer",
    "Computer Coding",
    "Computer Programming",
    "Computer Science",
    "Computer Scientist",
    "Computing",
    "Construction",
    "Cook",
    "Cookie",
    "Cooking",
    "Cool",
    "Cop",
    "Corn",
    "Corny",
    "Corporate",
    "Country",
    "Couple",
    "Covid",
    "Cow",
    "Cowboy",
    "Crab",
    "Cracker",
    "Cricket",
    "Cricketer",
    "Crocodile",
    "Cross the Road",
    "Crush",
    "Cycling",
    "Dad",
    "Dad Jokes",
    "Dallas Cowboys",
    "Dance",
    "Dancing",
    "Dark Humor",
    "Darkness",
    "Data Science",
    "Dating",
    "Day",
    "Deaf",
    "Death",
    "December",
    "Deer",
    "Definition",
    "Dental",
    "Dentist",
    "Depressed",
    "Depression",
    "Developer",
    "Diabetes",
    "Diarrhea",
    "Dieting",
    "Dinosaur",
    "Disney",
    "Divorce",
    "DnD",
    "Doctor",
    "Dog",
    "Dolphin",
    "Donald Trump",
    "Donkey",
    "Double Meaning",
    "Doughnut",
    "Dragon",
    "Draw",
    "Drawing",
    "Driving",
    "Drummer",
    "Dry",
    "Duck",
    "Dumb",
    "Dyslexia",
    "Ear",
    "Earthquake",
    "Easter",
    "Easter Bunny",
    "Economics",
    "Economy",
    "Education",
    "Egg",
    "Egypt",
    "Elderly People",
    "Electrician",
    "Electricity",
    "Elephant",
    "Elevator",
    "Elf",
    "Elf on the Shelf",
    "Elon Musk",
    "Emoji",
    "Employee",
    "Employment",
    "Engineer",
    "Engineering",
    "English",
    "English Teacher",
    "Exam",
    "Exam Tension",
    "Exercise",
    "Eye",
    "Face",
    "Facebook",
    "Fall",
    "Falling",
    "Family",
    "Famous",
    "Farm",
    "Farmer",
    "Farming",
    "Fart",
    "Father",
    "Father's Day",
    "February",
    "Feminist",
    "Fighting",
    "Finance",
    "Fire",
    "Firefighter",
    "Fish",
    "Fisherman",
    "Fishing",
    "Fitness",
    "Flamingo",
    "Flat Earther",
    "Flight",
    "Flirting",
    "Flower",
    "Flu",
    "Flying",
    "Food",
    "Foot",
    "Footballer",
    "Ford",
    "Forehead",
    "Fortnite",
    "Fox",
    "French",
    "Friday",
    "Friday the 13th",
    "Friendship",
    "Frog",
    "Fruit",
    "Funeral",
    "Game",
    "Gamer",
    "Garden",
    "Gardener",
    "Gardening",
    "Gasoline",
    "Gen Z",
    "Geography",
    "Geology",
    "Geometry",
    "Getting Older",
    "Ghost",
    "Gift",
    "Ginger",
    "Giraffe",
    "Girlfriend",
    "Glass",
    "Glasses",
    "Gnome",
    "Goat",
    "God",
    "Golf",
    "Golfer",
    "Goofy",
    "Google",
    "Goose",
    "Graduation",
    "Grammar",
    "Grandma",
    "Grandpa",
    "Greece",
    "Greek",
    "Guess What",
    "Guitar",
    "Guitar Player",
    "Guitarist",
    "Gun",
    "Gym",
    "Hair",
    "Haircut",
    "Hairdresser",
    "Hairline",
    "Halloween",
    "Hand",
    "Happiness",
    "Happy",
    "Harry Potter",
    "Harry Styles",
    "Head",
    "Healthy",
    "Heart",
    "Height",
    "Helen Keller",
    "Hell",
    "Hen",
    "Hike",
    "Hiker",
    "Hiking",
    "Hip Replacement",
    "Hip Surgery",
    "History",
    "Hockey",
    "Holiday",
    "Horror",
    "Horse",
    "Hospital",
    "Hot",
    "Hot Dog",
    "Hotel",
    "Human Resources",
    "Humor",
    "Hump Day",
    "Hunting",
    "Husband",
    "Ice",
    "Ice Cream",
    "Idea",
    "IKEA",
    "Illness",
    "In Love",
    "Independence Day",
    "India",
    "Indian",
    "Insect",
    "Instagram",
    "Insult",
    "Insurance",
    "Intelligence",
    "Intelligent",
    "Internet",
    "Interview",
    "iPhone",
    "Ireland",
    "Irish",
    "IT",
    "Italian",
    "Italy",
    "Jailhouse",
    "January",
    "Japan",
    "Jesus",
    "Job",
    "Juan",
    "July",
    "June",
    "Kangaroo",
    "Karen",
    "Ketchup",
    "Kids",
    "Kindergarten",
    "Kissing",
    "Knee",
    "Knock-Knock",
    "Koala",
    "Korea",
    "Labor Day",
    "Laffy Taffy",
    "Laughter",
    "Law",
    "Lawyer",
    "Leaf",
    "League",
    "League of Legends",
    "Lego",
    "Lemon",
    "Leprechaun",
    "Lettuce",
    "Library",
    "Life",
    "Light",
    "Light Bulb",
    "Lion",
    "Little Johnny",
    "Liverpool",
    "Llama",
    "Lobster",
    "Logic",
    "Long",
    "Love",
    "Lunch",
    "Man",
    "Management",
    "Manager",
    "Manchester United",
    "Mango",
    "March",
    "Marine",
    "Mario",
    "Marketer",
    "Marketing",
    "Marriage",
    "Marvel",
    "Math",
    "Math Teacher",
    "Mathematician",
    "May",
    "McDonald's",
    "Meat",
    "Mechanic",
    "Medical",
    "Mermaid",
    "Message",
    "Messi",
    "Mexico",
    "Michael Jackson",
    "Military",
    "Milk",
    "Millennial",
    "Minecraft",
    "Minion",
    "Mom",
    "Monday",
    "Money",
    "Monkey",
    "Month",
    "Moon",
    "Moose",
    "Mormon",
    "Morning",
    "Mosquito",
    "Moth",
    "Mother-in-Law",
    "Mother's Day",
    "Motivation",
    "Motivational",
    "Motorbike",
    "Motorcycle",
    "Mouse",
    "Movie",
    "Mummy",
    "Mushroom",
    "Music",
    "Muslim",
    "Mustache",
    "Nacho",
    "Nacho Cheese",
    "Name",
    "Narcissism",
    "Narcissist",
    "National Pi Day",
    "Navy",
    "Nerd",
    "New Year",
    "New Year Resolution",
    "New York",
    "No Arms No Legs",
    "Non-Vegetarian",
    "North Korea",
    "Northerner",
    "Nose",
    "November",
    "Number",
    "Nun",
    "Nurse",
    "Nut",
    "Observational",
    "Ocean",
    "October",
    "Octopus",
    "Office",
    "Ohio",
    "Old",
    "Old Age",
    "On Time",
    "One-Liners",
    "Onion",
    "Online",
    "Operation",
    "Orange",
    "Otter",
    "Owl",
    "Paint",
    "Painter",
    "Pancake",
    "Panda",
    "Paper",
    "Parent",
    "Parrot",
    "Party",
    "Pasta",
    "Peach",
    "Peanut",
    "Pee",
    "Pencil",
    "Penguin",
    "Penny",
    "Pepito",
    "Periodic Table",
    "Pharmacist",
    "Pharmacy",
    "PhD",
    "Philosopher",
    "Philosophy",
    "Phone",
    "Photo",
    "Physical Therapist",
    "Physicist",
    "Physics",
    "Pi",
    "Pianist",
    "Piano",
    "Pick up Lines",
    "Pickle",
    "Picture",
    "Pie",
    "Pig",
    "Pilot",
    "Pineapple",
    "Pinterest",
    "Pirate",
    "Pizza",
    "Planet",
    "Plant",
    "Planting",
    "Play",
    "Playing",
    "Plumber",
    "Poet",
    "Poetry",
    "Pokémon",
    "Poland",
    "Polar Bear",
    "Police",
    "Police Officer",
    "Policeman",
    "Politics",
    "Poop",
    "Poor",
    "Popcorn",
    "Popsicle",
    "Popsicle Stick",
    "Portugal",
    "Portuguese",
    "Potato",
    "Pregnant",
    "Preschool",
    "Preschooler",
    "Priest",
    "Prison",
    "Prisoner",
    "Profession",
    "Programmer",
    "Pronoun",
    "Psychiatrist",
    "Psychiatry",
    "Psychology",
    "Puerto Rico",
    "Pumpkin",
    "Punchline",
    "Puns",
    "Puzzle",
    "Question",
    "Rabbit",
    "Race",
    "Racing",
    "Ramadan",
    "Rapper",
    "Rat",
    "Reading",
    "Real Estate",
    "Real Estate Agent",
    "Red Panda",
    "Redhead",
    "Redneck",
    "Registered Nurse",
    "Reindeer",
    "Relationship",
    "Relationships",
    "Religion",
    "Restaurant",
    "Restroom",
    "Retirement",
    "Roast",
    "Roblox",
    "Robot",
    "Rock",
    "Roman",
    "Romance",
    "Romantic",
    "Rome",
    "Roof",
    "Roofer",
    "Roofing",
    "Rooster",
    "Rose",
    "Roses Are Red Violets Are Blue",
    "Run",
    "Runner",
    "Running",
    "Sad",
    "Sadness",
    "Sailor",
    "Salad",
    "Sales",
    "San Francisco 49er",
    "Sandwich",
    "Santa",
    "Santa-Banta",
    "Saturday",
    "Sausage",
    "Scarecrow",
    "Scared",
    "Scary",
    "School",
    "Science",
    "Scientist",
    "Sea",
    "Seafood",
    "Seagull",
    "Season",
    "Self-Deprecating",
    "Senior",
    "September",
    "Shakespeare",
    "Shark",
    "Sheep",
    "Shoe",
    "Short People",
    "Shrek",
    "Singer",
    "Single",
    "Siri",
    "Sister",
    "Skeleton",
    "Skinny",
    "Slave",
    "Sleep",
    "Sleeping",
    "Sloth",
    "Small",
    "Smart",
    "Smiling",
    "Smoke",
    "Smoker",
    "Smoking",
    "Snail",
    "Snake",
    "Snow",
    "Snowman",
    "So Dumb",
    "So Fat",
    "So Hot",
    "So Old",
    "So Short",
    "So Stupid",
    "So Ugly",
    "Soccer",
    "Sofa King",
    "Song",
    "Southerner",
    "Space",
    "Spain",
    "Spanish",
    "Spanish Language",
    "Spectacles",
    "Speech",
    "Spell",
    "Spelling",
    "Spider",
    "Spider-Man",
    "SpongeBob",
    "Sport",
    "Sports",
    "Spring",
    "Squirrel",
    "St. Patrick's Day",
    "Star Trek",
    "Star Wars",
    "Statistic",
    "Statistician",
    "Status",
    "Stephen Hawking",
    "Stranger Things",
    "Strawberry",
    "Street",
    "Stress",
    "Student",
    "Study",
    "Studying",
    "Stupid",
    "Submarine",
    "Summer",
    "Sun",
    "Sunday",
    "Sunflower",
    "Super Mario",
    "Superhero",
    "Surgical",
    "Sushi",
    "Sweating Like",
    "Sweden",
    "Sweet",
    "Swim",
    "Swimming",
    "Swimming Pool",
    "T-Rex",
    "T-Shirt",
    "Taco",
    "Tailor",
    "Tall People",
    "Tattoo",
    "Tax",
    "Taylor Swift",
    "Tea",
    "Teacher",
    "Teaching",
    "Technology",
    "Teenager",
    "Tennis",
    "Tesla",
    "Texas",
    "Text",
    "Text Message",
    "Thanksgiving",
    "Therapist",
    "Therapy",
    "Thesaurus",
    "Thursday",
    "Tiger",
    "Tiger Woods",
    "TikTok",
    "Time",
    "Tinder",
    "Toast",
    "Toaster",
    "Toe",
    "Toilet",
    "Toilet Paper",
    "Toilet Roll",
    "Tomato",
    "Tooth",
    "Topical",
    "Tractor",
    "Train",
    "Travel",
    "Traveler",
    "Traveling",
    "Tree",
    "Trick",
    "Truck",
    "Trucker",
    "Trucking",
    "Tuesday",
    "Tuna",
    "Turkey",
    "Turtle",
    "Tweet",
    "Twin",
    "Twitter",
    "U.S. Marine",
    "Ugly",
    "UK",
    "Uncle",
    "Unicorn",
    "Uranus",
    "USA",
    "Valentine's Day",
    "Vampire",
    "Vegan",
    "Vegetable",
    "Vegetarian",
    "Vehicle",
    "Veteran's Day",
    "Video",
    "Video Game",
    "Viking",
    "Viola",
    "Violist",
    "Virus",
    "Volleyball",
    "Walks Into a Bar",
    "Water",
    "Watermelon",
    "Weather",
    "Website",
    "Wedding",
    "Wednesday",
    "Weekend",
    "Werewolf",
    "Whale",
    "What",
    "What Did",
    "What Do",
    "What Is",
    "WhatsApp",
    "Wheelchair",
    "Wife",
    "Wine",
    "Winter",
    "Witch",
    "Witchcraft",
    "Wolf",
    "Woman",
    "Wood",
    "Wooden",
    "Word",
    "Wordplay",
    "Work",
    "Work at Home",
    "Work Colleague",
    "Workday",
    "Worker",
    "Working",
    "Workout",
    "Workplace",
    "World of Warcraft",
    "Writing",
    "Yo Daddy",
    "Yo Mama",
    "Yoda",
    "Yoga",
    "You Might Be",
    "You So",
    "YouTube",
    "YouTuber",
    "Zombie",
    "Zoo",
    "Zoom",
]
